### ISSUE TITLE
Learn the difference between merging and rebasing and how to do it properly

### ISSUE THREAD

**Issue by AichaMbongo** [digital-explorers-2/budget-buddy#29]
" *I will ask next lesson for people to explain it and let's see if we all agree or if someone has another idea to the one presented* " - Raimo

Check the box below once you are sure you have understood, this task is due by the end of today

- [x] Martin 
- [x] Pauline
- [x] Hellen
- [x] Unika
- [x] Aicha

**Comment by Ndathi08** [comment]
Done

**Comment by mmwachira** [comment]
Understood to some extent

**Comment by AichaMbongo** [comment]
done
