### ISSUE TITLE
fork your group project into your personal account and see if you're able to deploy it through Vercel

### ISSUE THREAD

**Issue by AichaMbongo** [digital-explorers-2/budget-buddy#30]
once you have performed this task kindly tick your name

- [x] Unika
- [x] Hellen
- [x] Martin
- [x] Pauline
- [x] Aicha

**Comment by mmwachira** [comment]
Forked and deployed from my side

**Comment by AichaMbongo** [comment]
> Forked and deployed from my side

Great, I think the one who is left is Hellen @Ndathi08

**Comment by Ndathi08** [comment]
Done

**Comment by Paula-Wang** [comment]
I am having an error with my deployment. I will retry and tick again when completeted
